"""
Trade Analysis Script for ICT FVG Backtest
===========================================

This script analyzes the trade log CSV generated by ict_fvg_backtest.py
and provides additional insights and visualizations.

Usage: python analyze_trades.py
"""

import pandas as pd
import numpy as np
from datetime import datetime


def analyze_trades(trade_log_file='trade_log.csv'):
    """
    Analyze trades and provide detailed statistics.
    
    Args:
        trade_log_file: Path to the trade log CSV
    """
    print("="*80)
    print("ICT FVG TRADE ANALYSIS")
    print("="*80)
    
    # Load trade log
    df = pd.read_csv(trade_log_file)
    
    if df.empty:
        print("No trades found in log!")
        return
    
    print(f"\nTotal trades in log: {len(df)}")
    print(f"R:R ratios tested: {sorted(df['rr_ratio'].unique())}")
    
    # Analysis by R:R ratio
    for rr in sorted(df['rr_ratio'].unique()):
        df_rr = df[df['rr_ratio'] == rr].copy()
        
        print(f"\n{'='*80}")
        print(f"DETAILED ANALYSIS - {rr}R Target")
        print(f"{'='*80}")
        
        # Basic stats
        total = len(df_rr)
        wins = len(df_rr[df_rr['result'] == 'win'])
        losses = len(df_rr[df_rr['result'] == 'loss'])
        
        print(f"\n1. BASIC STATISTICS:")
        print(f"   Total Trades: {total}")
        print(f"   Wins: {wins} ({wins/total*100:.2f}%)")
        print(f"   Losses: {losses} ({losses/total*100:.2f}%)")
        
        # Direction analysis
        print(f"\n2. DIRECTION BREAKDOWN:")
        long_trades = len(df_rr[df_rr['direction'] == 'long'])
        short_trades = len(df_rr[df_rr['direction'] == 'short'])
        print(f"   Long trades: {long_trades} ({long_trades/total*100:.2f}%)")
        print(f"   Short trades: {short_trades} ({short_trades/total*100:.2f}%)")
        
        # Win rate by direction
        long_wr = len(df_rr[(df_rr['direction'] == 'long') & (df_rr['result'] == 'win')]) / long_trades * 100 if long_trades > 0 else 0
        short_wr = len(df_rr[(df_rr['direction'] == 'short') & (df_rr['result'] == 'win')]) / short_trades * 100 if short_trades > 0 else 0
        print(f"   Long win rate: {long_wr:.2f}%")
        print(f"   Short win rate: {short_wr:.2f}%")
        
        # P&L analysis
        print(f"\n3. P&L ANALYSIS:")
        total_pnl = df_rr['pnl'].sum()
        avg_win = df_rr[df_rr['result'] == 'win']['pnl'].mean() if wins > 0 else 0
        avg_loss = df_rr[df_rr['result'] == 'loss']['pnl'].mean() if losses > 0 else 0
        print(f"   Total P&L: ${total_pnl:.2f}")
        print(f"   Average Win: ${avg_win:.2f}")
        print(f"   Average Loss: ${avg_loss:.2f}")
        print(f"   Avg Win/Loss Ratio: {abs(avg_win/avg_loss):.3f}" if avg_loss != 0 else "   Avg Win/Loss Ratio: N/A")
        
        # Largest wins/losses
        largest_win = df_rr[df_rr['result'] == 'win']['pnl'].max() if wins > 0 else 0
        largest_loss = df_rr[df_rr['result'] == 'loss']['pnl'].min() if losses > 0 else 0
        print(f"   Largest Win: ${largest_win:.2f}")
        print(f"   Largest Loss: ${largest_loss:.2f}")
        
        # Trade duration analysis
        print(f"\n4. TRADE DURATION:")
        avg_duration = df_rr['bars_in_trade'].mean()
        min_duration = df_rr['bars_in_trade'].min()
        max_duration = df_rr['bars_in_trade'].max()
        print(f"   Average: {avg_duration:.1f} bars ({avg_duration:.1f} minutes)")
        print(f"   Minimum: {min_duration} bars")
        print(f"   Maximum: {max_duration} bars")
        
        # Winning vs losing trade duration
        avg_win_duration = df_rr[df_rr['result'] == 'win']['bars_in_trade'].mean() if wins > 0 else 0
        avg_loss_duration = df_rr[df_rr['result'] == 'loss']['bars_in_trade'].mean() if losses > 0 else 0
        print(f"   Avg winning trade: {avg_win_duration:.1f} bars")
        print(f"   Avg losing trade: {avg_loss_duration:.1f} bars")
        
        # Risk analysis
        print(f"\n5. RISK ANALYSIS:")
        avg_risk = df_rr['risk'].mean()
        min_risk = df_rr['risk'].min()
        max_risk = df_rr['risk'].max()
        print(f"   Average risk per trade: ${avg_risk:.2f}")
        print(f"   Minimum risk: ${min_risk:.2f}")
        print(f"   Maximum risk: ${max_risk:.2f}")
        
        # Consecutive wins/losses
        print(f"\n6. STREAKS:")
        streak = []
        current_streak = 0
        last_result = None
        
        for result in df_rr['result']:
            if result == last_result:
                current_streak += 1
            else:
                if last_result is not None:
                    streak.append((last_result, current_streak))
                current_streak = 1
                last_result = result
        
        if last_result is not None:
            streak.append((last_result, current_streak))
        
        max_win_streak = max([s[1] for s in streak if s[0] == 'win'], default=0)
        max_loss_streak = max([s[1] for s in streak if s[0] == 'loss'], default=0)
        
        print(f"   Max consecutive wins: {max_win_streak}")
        print(f"   Max consecutive losses: {max_loss_streak}")
        
        # Monthly breakdown if entry_time exists
        if 'entry_time' in df_rr.columns:
            print(f"\n7. TIME-BASED ANALYSIS:")
            df_rr['entry_time'] = pd.to_datetime(df_rr['entry_time'])
            df_rr['month'] = df_rr['entry_time'].dt.to_period('M')
            df_rr['year'] = df_rr['entry_time'].dt.year
            
            # Trades per year
            trades_per_year = df_rr.groupby('year').size()
            print(f"\n   Trades per year:")
            for year, count in trades_per_year.items():
                year_pnl = df_rr[df_rr['year'] == year]['pnl'].sum()
                year_wr = len(df_rr[(df_rr['year'] == year) & (df_rr['result'] == 'win')]) / count * 100
                print(f"   {year}: {count} trades, ${year_pnl:.2f} P&L, {year_wr:.1f}% WR")
            
            # Best/worst months
            monthly_pnl = df_rr.groupby('month')['pnl'].sum().sort_values(ascending=False)
            print(f"\n   Best 5 months:")
            for month, pnl in monthly_pnl.head(5).items():
                print(f"   {month}: ${pnl:.2f}")
            
            print(f"\n   Worst 5 months:")
            for month, pnl in monthly_pnl.tail(5).items():
                print(f"   {month}: ${pnl:.2f}")
        
        # FVG type analysis
        print(f"\n8. FVG TYPE BREAKDOWN:")
        bullish_fvg = len(df_rr[df_rr['fvg_type'] == 'bullish'])
        bearish_fvg = len(df_rr[df_rr['fvg_type'] == 'bearish'])
        print(f"   Bullish FVG trades: {bullish_fvg} ({bullish_fvg/total*100:.2f}%)")
        print(f"   Bearish FVG trades: {bearish_fvg} ({bearish_fvg/total*100:.2f}%)")
        
        bullish_wr = len(df_rr[(df_rr['fvg_type'] == 'bullish') & (df_rr['result'] == 'win')]) / bullish_fvg * 100 if bullish_fvg > 0 else 0
        bearish_wr = len(df_rr[(df_rr['fvg_type'] == 'bearish') & (df_rr['result'] == 'win')]) / bearish_fvg * 100 if bearish_fvg > 0 else 0
        print(f"   Bullish FVG win rate: {bullish_wr:.2f}%")
        print(f"   Bearish FVG win rate: {bearish_wr:.2f}%")
    
    print(f"\n{'='*80}")
    print("Analysis Complete!")
    print("="*80)


def main():
    """Main execution function."""
    try:
        analyze_trades()
    except FileNotFoundError:
        print("Error: trade_log.csv not found!")
        print("Please run ict_fvg_backtest.py first to generate the trade log.")
    except Exception as e:
        print(f"Error during analysis: {str(e)}")


if __name__ == "__main__":
    main()
